#pragma once
#include "common_include.hpp"

extern const uint8_t LDS_UNIVERSAL_KEY[16];

enum class Format
{
    UINT8,
    UINT16,
    UINT32,
    UINT64,
    INT8,
    INT16,
    INT32,
    INT64,
    FLOAT,
    DOUBLE,
    CHAR_P
};

enum class Tag : uint8_t
{
    CHECKSUM = 0x01,
    UNIX_TIME_STAMP = 0x02,
    MISSION_ID = 0x03,
    PLATFORM_TAIL_NUMBER = 0x04,
    PLATFORM_HEADING_ANGLE = 0x05,
    PLATFORM_PITCH_ANGLE = 0x06,
    PLATFORM_ROLL_ANGLE = 0x07,
    PLATFORM_TRUE_AIRSPEED = 0x08,
    PLATFORM_INDICATED_AIRSPEED = 0x09,
    PLATFORM_DESIGNATION = 0x0A,
    IMAGE_SOURCE_SENSOR = 0x0B,
    IMAGE_COORDINATE_SYSTEM = 0x0C,
    SENSOR_LATITUDE = 0x0D,
    SENSOR_LONGITUDE = 0x0E,
    SENSOR_TRUE_ALTITUDE = 0x0F,
    SENSOR_HORIZONTAL_FOV = 0x10,
    SENSOR_VERTICAL_FOV = 0x11,
    SENSOR_RELATIVE_AZIMUTH_ANGLE = 0x12,
    SENSOR_RELATIVE_ELEVATION_ANGLE = 0x13,
    SENSOR_RELATIVE_ROLL_ANGLE = 0x14,
    SLANT_RANGE = 0x15,
    TARGET_WIDTH = 0x16,
    FRAME_CENTER_LATITUDE = 0x17,
    FRAME_CENTER_LONGITUDE = 0x18,
    FRAME_CENTER_ELEVATION = 0x19,
    OFFSET_CORNER_LATITUDE_POINT_1 = 0x1A,
    OFFSET_CORNER_LONGITUDE_POINT_1 = 0x1B,
    OFFSET_CORNER_LATITUDE_POINT_2 = 0x1C,
    OFFSET_CORNER_LONGITUDE_POINT_2 = 0x1D,
    OFFSET_CORNER_LATITUDE_POINT_3 = 0x1E,
    OFFSET_CORNER_LONGITUDE_POINT_3 = 0x1F,
    OFFSET_CORNER_LATITUDE_POINT_4 = 0x20,
    OFFSET_CORNER_LONGITUDE_POINT_4 = 0x21,
    ICING_DETECTED = 0x22,
    WIND_DIRECTION = 0x23,
    WIND_SPEED = 0x24,
    STATIC_PRESSURE = 0x25,
    DENSITY_ALTITUDE = 0x26,
    OUTSIDE_AIR_TEMPERATURE = 0x27,
    TARGET_LOCATION_LATITUDE = 0x28,
    TARGET_LOCATION_LONGITUDE = 0x29,
    TARGET_LOCATION_ELEVATION = 0x2A,
    TARGET_TRACK_GATE_WIDTH = 0x2B,
    TARGET_TRACK_GATE_HEIGHT = 0x2C,
    TARGET_ERROR_ESTIMATE_CE90 = 0x2D,
    TARGET_ERROR_ESTIMATE_LE90 = 0x2E,
    GENERIC_FLAG_DATA1 = 0x2F,
    SECURITY_LOCAL_METADATA_SET = 0x30,
    DIFFERENTIAL_PRESSURE = 0x31,
    PLATFORM_ANGLE_OF_ATTACK = 0x32,
    PLATFORM_VERTICAL_SPEED = 0x33,
    PLATFORM_SIDESLIP_ANGLE = 0x34,
    AIRFIELD_BAROMETRIC_PRESSURE = 0x35,
    AIRFIELD_ELEVATION = 0x36,
    RELATIVE_HUMIDITY = 0x37,
    PLATFORM_GROUND_SPEED = 0x38,
    GROUND_RANGE = 0x39,
    PLATFORM_FUEL_REMAINING = 0x3A,
    PLATFORM_CALL_SIGN = 0x3B,
    WEAPON_LOAD = 0x3C,
    WEAPON_FIRED = 0x3D,
    LASER_PRF_CODE = 0x3E,
    SENSOR_FOV_NAME = 0x3F,
    PLATFORM_MAGNETIC_HEADING = 0x40,
    UAS_LDS_VERSION_NUMBER = 0x41,
    TARGET_LOCATION_COVARIANCE_MATRIX = 0x42,
    ALTERNATE_PLATFORM_LATITUDE = 0x43,
    ALTERNATE_PLATFORM_LONGITUDE = 0x44,
    ALTERNATE_PLATFORM_ALTITUDE = 0x45,
    ALTERNATE_PLATFORM_NAME = 0x46,
    ALTERNATE_PLATFORM_HEADING = 0x47,
    EVENT_START_TIME_UTC = 0x48,
    RVT_LOCAL_DATA_SET = 0x49,
    VMTI_LOCAL_DATA_SET = 0x4A,
    SENSOR_ELLIPSOID_HEIGHT = 0x4B,
    ALTERNATE_PLATFORM_ELLIPSOID_HEIGHT = 0x4C,
    OPERATIONAL_MODE = 0x4D,
    FRAME_CENTER_HEIGHT_ABOVE_ELLIPSOID = 0x4E,
    SENSOR_NORTH_VELOCITY = 0x4F,
    SENSOR_EAST_VELOCITY = 0x50,
    IMAGE_HORIZON_PIXEL_PACK = 0x51,
    CORNER_LATITUDE_POINT_1 = 0x52,
    CORNER_LONGITUDE_POINT_1 = 0x53,
    CORNER_LATITUDE_POINT_2 = 0x54,
    CORNER_LONGITUDE_POINT_2 = 0x55,
    CORNER_LATITUDE_POINT_3 = 0x56,
    CORNER_LONGITUDE_POINT_3 = 0x57,
    CORNER_LATITUDE_POINT_4 = 0x58,
    CORNER_LONGITUDE_POINT_4 = 0x59,
    PLATFORM_PITCH_ANGLE_FULL = 0x5A,
    PLATFORM_ROLL_ANGLE_FULL = 0x5B,
    PLATFORM_ANGLE_OF_ATTACK_FULL = 0x5C,
    PLATFORM_SIDESLIP_ANGLE_FULL = 0x5D
};

struct GenericValue
{
    Format type;
    union
    {
        uint8_t uint8_value;
        uint16_t uint16_value;
        uint32_t uint32_value;
        uint64_t uint64_value;
        int8_t int8_value;
        int16_t int16_value;
        int32_t int32_value;
        int64_t int64_value;
        float float_value;
        double double_value;
        char *charp_value;
    };
};

struct ValueRange
{
    GenericValue min;
    GenericValue max;
};

struct Field
{
    Tag key;
    Format value_format;
    Format encoded_format;
    uint8_t len;
    ValueRange range;
};

static constexpr size_t FIELD_COUNT = 0x5E;
extern Field FieldMap[FIELD_COUNT];